# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "simple-file-uploader"
client_id = "c79316471b1706092375856a9b9d4576"
application_url = "https://harbour-boats-geology-cartridge.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://harbour-boats-geology-cartridge.trycloudflare.com/auth/callback",
  "https://harbour-boats-geology-cartridge.trycloudflare.com/auth/shopify/callback",
  "https://harbour-boats-geology-cartridge.trycloudflare.com/api/auth/callback",
  "https://harbour-boats-geology-cartridge.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-9d7cc73d.myshopify.com"
